# Generated by Django 2.2.7 on 2019-12-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('collegeCareer', models.CharField(max_length=50)),
            ],
        ),
    ]
